<a href="https://colab.research.google.com/github/reinaldoyungh/Python/blob/main/IA_CATEGORIZAR_COMENTARIOS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install -q groq
import os
from google.colab import userdata

os.environ["GROQ_API_KEY"] = userdata.get('GROQ_API_KEY')
from groq import Groq
client = Groq()

import pandas as pd

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 142.3/142.3 kB 2.7 MB/s eta 0:00:00

In [2]:

def chama_IA(perguntas):
    all_responses = []
    for pergunta_individual in perguntas:
        response_stream = client.chat.completions.create(
          model="openai/gpt-oss-20b",
          messages=[
            {
              "role": "user",
              "content": pergunta_individual
            }
          ],
          temperature=1,
          max_completion_tokens=1024,
          top_p=1,
          reasoning_effort="medium",
          stream=True,
          stop=None
        )

        collected_text = ""
        for chunk in response_stream:
            if chunk.choices and chunk.choices[0].delta.content:
                collected_text += chunk.choices[0].delta.content
        all_responses.append(collected_text)
    return all_responses

In [4]:
lista_reviews = []
with open('reviews.csv', 'r') as arquivo:
  for linha in arquivo:
    lista_reviews.append(linha.strip())

In [5]:
import io

# Convert the list of CSV strings into a pandas DataFrame
df_reviews = pd.read_csv(io.StringIO('\n'.join(lista_reviews)))

# Display the 'reviewerName' and 'reviewText' columns
display(df_reviews[['reviewerName', 'reviewText']])

,reviewerName,reviewText
0,1K3,it works as expected. I should have sprung for...
1,1m2,This think has worked out great.Had a diff. br...
2,2&amp;1/2Men,"Bought it with Retail Packaging, arrived legit..."
3,2Cents!,It's mini storage. It doesn't do anything els...
4,2K1Toaster,I have it in my phone and it never skips a bea...
5,98020,"It works, but file writes are a bit slower tha..."
6,"Abdulrahman J. Alrashed ""dr34m3r""","I bought 2 of those SanDisk 32 GB microSD , us..."
7,"Abel Feliciano ""Ace Master""",The memory card is an excellent condition and ...
8,Abraham Arturo Meza Marin,I bougth this micro SD card after some trubles...
9,"Abused Commuter ""abused_commuter""",Ordered this for a Galaxy S3. Lasted a few mo...
10,abushaheed,more like 8mb/s in my Note 10.1 and that's usi...
11,Ace of Sevens,"I used this for a few months in my phone, then..."
12,A. Cho,"everything about it was great, except for the ..."
13,ACZ,Used in my phone it's plenty fast and works ju...
14,"Adam Wright ""Electrical Engineer""",This card advertises itself as UHS1 but it's a...
15,A. Hejazi,I bought this SD card for my android phone thi...
16,ahhsimon,good card. work as describes. haven't had any ...
17,A.J. Matheson,I got this because I just couldn't pass up the...
18,Alan,It works but the actual R/W speeds are 18/8 MB...
19,Albert,Does it's job and fairly cheap for what it's w...
20,Alejandro Hernndez,Still don't feel is very fast or is just my ph...
21,Aleksandar Milivojevic,I bought 64GB version of the card to use with ...
22,"Ali Etezadkhah ""Ali""",I have an old SanDisk SD card that still works...
23,A. Liu,Used it in my Galaxy Note 2 for the past 16 mo...
24,Alton L Spencer,Worked great in my galaxy s4--until it didn't ...
25,A. Marte,I bought this on August of 2013. As of April ...
26,"Amazon Customer ""fiction buff""",So this product is a large disappointment...bo...
27,Amazon Customer,I will keep it short and sweet for potential b...
28,Amazon Customer,"The package arrived on time, it's very well pa..."
29,Amazon Customer,"Does what it says. Hasn't broken yet, and I ho..."
30,Amazon Customer,Thus microSD card worked fine for a year in my...
31,"Amazon Customer ""Music Fan""","I think this is probably a fine product, but i..."
32,"Amazon Customer ""PawsitivelySafe""",I have two of these and use them for my Galazy...
33,Amazon Fan,I join the long list of customers who have had...
34,Amazon Shopper,"I do not get the advertised speed of 30MB/s, m..."
35,Andrew M. Swiatek,the micro sd works great as described. but bew...
36,anonomous,than i expected. I don't know if it would kill...
37,"A. Shieh ""eff.org""","Reliable and inexpensive. However, it's quite ..."
38,astraelraen,I bought this primarily to use in my Surface P...
39,"Zeality ""N2iT""",I really don't know what to think about this I...

In [7]:
reviews_to_classify = df_reviews['reviewText'].tolist()

# Prepare questions for the LLM to classify sentiment
perguntas_sentimento = [
    f"Classifique o sentimento da seguinte avaliação do cliente como Positivo, Negativo ou Neutro: {review}"
    for review in reviews_to_classify
]

# Call the LLM function to get sentiments
sentimentos = chama_IA(perguntas_sentimento)

# Add the sentiments as a new column to the DataFrame
df_reviews['sentimento'] = df_reviews['sentimento'].str.replace('**', '', regex=False).str.strip()

# Display the DataFrame with the new sentiment column
display(df_reviews[['reviewerName', 'reviewText', 'sentimento']].head())

   reviewerName                                         reviewText sentimento
0           1K3  it works as expected. I should have sprung for...     Neutro
1           1m2  This think has worked out great.Had a diff. br...   Positivo
2  2&amp;1/2Men  Bought it with Retail Packaging, arrived legit...   Positivo
3       2Cents!  It's mini storage.  It doesn't do anything els...   Positivo
4    2K1Toaster  I have it in my phone and it never skips a bea...   Positivo

In [ ]:
df_reviews.to_csv('reviews_avaliados.csv', index=False)
print('DataFrame salvo como reviews_avaliados.csv')

In [12]:
df_reviews_negativas = df_reviews[df_reviews["sentimento"] == "Negativo"]
df_reviews_negativas

,reviewerID,asin,reviewerName,reviewText,unixReviewTime,reviewTime,day_diff,helpful_yes,total_vote,sentimento
6,AF24M1HKIZ7QC,B007WTAJTO,"Abdulrahman J. Alrashed ""dr34m3r""","I bought 2 of those SanDisk 32 GB microSD , us...",1375488000,08/03/2013,640,0,0,Negativo
8,A1FKE13D77L3Y3,B007WTAJTO,Abraham Arturo Meza Marin,I bougth this micro SD card after some trubles...,1361232000,19/02/2013,657,0,0,Negativo
9,A1X1FX3NSOFCT3,B007WTAJTO,"Abused Commuter ""abused_commuter""",Ordered this for a Galaxy S3. Lasted a few mo...,1374278400,20/07/2013,506,0,1,Negativo
10,A3RV1L35IPTV61,B007WTAJTO,abushaheed,more like 8mb/s in my Note 10.1 and that's usi...,1357430400,01/06/2013,555,0,0,Negativo
11,A2RJ7DAL63MN1F,B007WTAJTO,Ace of Sevens,"I used this for a few months in my phone, then...",1391126400,31/01/2014,311,0,0,Negativo
14,APAEBFIM1588A,B007WTAJTO,"Adam Wright ""Electrical Engineer""",This card advertises itself as UHS1 but it's a...,1378684800,09/09/2013,455,1,1,Negativo
15,A1JOXGZH55JMHW,B007WTAJTO,A. Hejazi,I bought this SD card for my android phone thi...,1386806400,12/12/2013,361,0,0,Negativo
18,A28CTDM7OP0RAR,B007WTAJTO,Alan,It works but the actual R/W speeds are 18/8 MB...,1395705600,25/03/2014,258,0,0,Negativo
19,A1NA2JGI3GNDN2,B007WTAJTO,Albert,Does it's job and fairly cheap for what it's w...,1399161600,05/04/2014,247,0,0,Negativo
21,A1UM44ILLZCEI1,B007WTAJTO,Aleksandar Milivojevic,I bought 64GB version of the card to use with ...,1364947200,04/03/2013,644,1,1,Negativo
22,A2T71JNR3C2DY1,B007WTAJTO,"Ali Etezadkhah ""Ali""",I have an old SanDisk SD card that still works...,1371859200,22/06/2013,534,0,0,Negativo
23,A87U7LY9OKZNY,B007WTAJTO,A. Liu,Used it in my Galaxy Note 2 for the past 16 mo...,1398988800,05/02/2014,306,0,0,Negativo
24,A277QWS5WF6DWI,B007WTAJTO,Alton L Spencer,Worked great in my galaxy s4--until it didn't ...,1401148800,27/05/2014,195,0,0,Negativo
25,A1WWPAQ1DD6BQC,B007WTAJTO,A. Marte,I bought this on August of 2013. As of April ...,1403654400,25/06/2014,166,1,1,Negativo
26,A3FY6V3LXP8SSL,B007WTAJTO,"Amazon Customer ""fiction buff""",So this product is a large disappointment...bo...,1349136000,10/02/2012,1032,0,0,Negativo
27,A3DXCQV1U6QLTS,B007WTAJTO,Amazon Customer,I will keep it short and sweet for potential b...,1360195200,02/07/2013,524,0,0,Negativo
30,A308JP3BK4VAL7,B007WTAJTO,Amazon Customer,Thus microSD card worked fine for a year in my...,1398643200,28/04/2014,224,0,3,Negativo
31,A392ZR68AKLDCK,B007WTAJTO,"Amazon Customer ""Music Fan""","I think this is probably a fine product, but i...",1374796800,26/07/2013,500,1,1,Negativo
34,A1Z7FZP81N8CDU,B007WTAJTO,Amazon Shopper,"I do not get the advertised speed of 30MB/s, m...",1394755200,14/03/2014,269,0,1,Negativo
35,A1T8FVB93QQNOM,B007WTAJTO,Andrew M. Swiatek,the micro sd works great as described. but bew...,1372464000,29/06/2013,527,0,0,Negativo
36,A3K1JZPUXSADRJ,B007WTAJTO,anonomous,than i expected. I don't know if it would kill...,1362182400,03/02/2013,673,0,2,Negativo
37,A1D07XDTMWV0A5,B007WTAJTO,"A. Shieh ""eff.org""","Reliable and inexpensive. However, it's quite ...",1385769600,30/11/2013,373,0,0,Negativo
38,A1HKW2TELCHGLL,B007WTAJTO,astraelraen,I bought this primarily to use in my Surface P...,1391040000,30/01/2014,312,0,0,Negativo
39,A3P86Z2D81VLYV,B007WTAJTO,"Zeality ""N2iT""",I really don't know what to think about this I...,1396137600,30/03/2014,253,0,0,Negativo

In [14]:
resenhas_negativas = df_reviews_negativas["reviewText"]
resenhas_negativas

6     I bought 2 of those SanDisk 32 GB microSD , us...
8     I bougth this micro SD card after some trubles...
9     Ordered this for a Galaxy S3.  Lasted a few mo...
10    more like 8mb/s in my Note 10.1 and that's usi...
11    I used this for a few months in my phone, then...
14    This card advertises itself as UHS1 but it's a...
15    I bought this SD card for my android phone thi...
18    It works but the actual R/W speeds are 18/8 MB...
19    Does it's job and fairly cheap for what it's w...
21    I bought 64GB version of the card to use with ...
22    I have an old SanDisk SD card that still works...
23    Used it in my Galaxy Note 2 for the past 16 mo...
24    Worked great in my galaxy s4--until it didn't ...
25    I bought this on August of 2013.  As of April ...
26    So this product is a large disappointment...bo...
27    I will keep it short and sweet for potential b...
30    Thus microSD card worked fine for a year in my...
31    I think this is probably a fine product, but i...
34    I do not get the advertised speed of 30MB/s, m...
35    the micro sd works great as described. but bew...
36    than i expected. I don't know if it would kill...
37    Reliable and inexpensive. However, it's quite ...
38    I bought this primarily to use in my Surface P...
39    I really don't know what to think about this I...
Name: reviewText, dtype: object

In [16]:
resenhas_negativas_unidas = "#####".join(resenhas_negativas)

In [24]:
resposta_categorias = [
    f"""Você é um analista de dados, vou te passar muitas resenhas negativas de analises de um produto e eu quero que você encontre cinco categorias distintas para os tipos de reclamações, em portugues. Quero que você me retorne as cinco categorias. Cada categoria deve ser definida APENAS uma palavra. Além disso não escreva nada mais além das cinco categoria. Quero que elas sejam retornadas separadas por víngulas e em letras minusculas e sem acentos graficos.
    Exemplos: 'eletronicos, roupas, alimentos, viagens, brinquedos'

    Aqui estão as resenhas negativas separadas por #####: {resenhas_negativas_unidas}"""
]

resposta_IA = chama_IA(resposta_categorias)
print (resposta_IA)

['durabilidade, velocidade, compatibilidade, corrupcao, engano']

In [27]:
lista_categorias = resposta_IA[0].split(sep=', ')
lista_categorias

['durabilidade', 'velocidade', 'compatibilidade', 'corrupcao', 'engano']